#!/bin/bash
# first argument: first argument: remote, second argument: remote path

echo "copying to $1:$2"

rsync -avzhe ssh --exclude 'out' --exclude '.git' --exclude '.gitignore' --exclude-from '.gitignore' --delete . $1:$2
