#!/bin/bash

ssh $1 'NSESS=`screen -ls | grep "(\(De\|At\)tached)" | wc -l` && if [ $NSESS -eq 0 ] ; then echo "No experiments running" ; else echo "WARNING! $NSESS experiments are running" ; echo ; fi && exit $NSESS'
