#!/bin/bash
# first argument: file to run, second argument: remote, third argument: remote path, fourth argument: description

echo "running $1 on $2:$3"
echo "description: $4"

FN=$(date +%s)

ssh $2 "mkdir -p $3/out/$FN && echo $4 > $3/out/$FN/description"

$(dirname $0)/remcopy $2 $3

ssh $2 "cd $3 && chmod +x $1 && screen -d -m /bin/bash -c \"./$1 out/$FN > out/$FN/stdout.txt 2> out/$FN/stderr.txt\""
