#!/bin/bash
# first argument: file to run, second argument: remote, third argument: remote path

echo "running $1 on $2:$3"

FN=$(date +%s)

ssh $2 "mkdir -p $3/out/$FN"

rsync -avzhre ssh --exclude 'out' --exclude-from '.gitignore' --delete . $2:$3

ssh $2 "cd $3 && chmod +x $1 && screen -d -m /bin/bash -c \"./$1 out/$FN > out/$FN/stdout.txt 2> out/$FN/stderr.txt\""
